apiVersion: tekton.dev/v1
kind: Pipeline
spec:
  tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
          - name: kind
            value: task
          - name: name
            value: init
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.2@sha256:ebfb603b73c2e1500fa1d2c757a585bc2da5043afe0798abdf61466e26fd2b0c
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1@sha256:39efcb7d049d84feccce65e589996a89b19ab7c9f504015c3792e3daee697da3
