apiVersion: tekton.dev/v1
kind: Pipeline
spec:
  tasks:
    - name: init
      taskRef:
        resolver: bundles
        params:
          - name: kind
            value: task
          - name: name
            value: init
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-init:0.2@sha256:ebfb603b73c2e1500fa1d2c757a585bc2da5043afe0798abdf61466e26fd2b0c
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone-oci-ta
          - name: bundle
            value: quay.io/redhat-appstudio-tekton-catalog/task-git-clone:0.1@sha256:b99d377c3e28fad51009849f6ba3a1bc47d1dc4c46f470ea12ed7b1b444599d7
